using System;
using System.Collections.Generic;
using UnityEngine;

namespace BorrowedHex.Presentation.Audio
{
    /// <summary>
    /// Every cue in Assets/SFX/manifest.json, by its manifest name, with its clip variations.
    ///
    /// Why an asset and not Resources.Load by path: the WAV masters live in Assets/SFX, outside
    /// any Resources folder, and moving 800 files (and their GUIDs) would churn the audio
    /// commits. This one asset under Resources references them instead, so a player build
    /// includes exactly the clips the manifest names. It is regenerated by
    /// BorrowedHex/Audio/Rebuild Audio Library (AudioLibraryBuilder) whenever the manifest changes.
    /// </summary>
    public sealed class AudioLibrary : ScriptableObject
    {
        public const string ResourcePath = "Audio/AudioLibrary";

        [Serializable]
        public sealed class Cue
        {
            public string name;
            public bool loop;
            public AudioClip[] clips;
        }

        public List<Cue> cues = new List<Cue>();

        Dictionary<string, Cue> byName;

        /// <summary>The cue with this manifest name, or null (a missing cue is silent, never an error).</summary>
        public Cue Find(string name)
        {
            if (byName == null)
            {
                byName = new Dictionary<string, Cue>(cues.Count);
                foreach (var c in cues) if (c != null && !string.IsNullOrEmpty(c.name)) byName[c.name] = c;
            }
            return name != null && byName.TryGetValue(name, out var cue) ? cue : null;
        }

        static AudioLibrary cached;
        static bool looked;

        /// <summary>The shipped library, loaded once; null if it has not been built yet.</summary>
        public static AudioLibrary Load()
        {
            if (!looked) { cached = Resources.Load<AudioLibrary>(ResourcePath); looked = true; }
            return cached;
        }
    }
}
